apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-named-port
  name: nginx-named-port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-named-port
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-named-port
        application: v1
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        ports:
        - containerPort: 80
          name: http-port
