apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: '200m'
      memory: '256Mi'
    defaultRequest:
      cpu: '100m'
      memory: '128Mi'
    max:
      cpu: '1'
      memory: '512Mi'
    min:
      cpu: '50m'
      memory: '64Mi'
    type: Container